`ifndef __GUARD_APB_RSP_ITEM_SV__
`define __GUARD_APB_RSP_ITEM_SV__ 0

`include "object/apb_seq_item.sv"

/**
 * @class apb_rsp_item
 * @brief Response item class for APB (Advanced Peripheral Bus) transactions.
 *
 * This class extends the apb_seq_item base class to represent the response
 * generated by an APB slave device in response to APB transactions. In the
 * context of the UART testbench, this item is used to model the data and
 * status returned from APB read operations or acknowledgments from write
 * operations.
 *
 * The response item typically includes fields such as:
 * - Read data (prdata) from the slave
 * - Error indicators (pslverr) if the transaction failed
 * - Ready signal (pready) indicating completion
 *
 * This class is part of the UVM (Universal Verification Methodology) testbench
 * environment for verifying the APB UART IP core.
 */
class apb_rsp_item extends apb_seq_item;

  `uvm_object_utils(apb_rsp_item)

  // TODO: Define sequence item fields such as prdata, pslverr, pready, etc.
  // These fields should correspond to the APB protocol signals for responses.

  /**
   * @brief Constructor for the apb_rsp_item class.
   *
   * Initializes the response item with the given name. Calls the parent
   * constructor to ensure proper UVM object initialization.
   *
   * @param name The name of the UVM object instance (default: "apb_rsp_item").
   */
  function new(string name = "apb_rsp_item");
    super.new(name);
  endfunction : new

endclass

`endif
